export const componentLibrary = [
  {
    name: "Badge",
    figma: "Status",
    variants: ["warning", "success", "error"],
    firstSeen: "Flight Deck",
  },
  {
    name: "Button",
    figma: "Buttons / _Base Button",
    variants: ["primary", "secondary", "outline", "text"],
    sizes: ["base", "small"],
    firstSeen: "Log in",
  },
  {
    name: "TextField",
    figma: "Floating Label / input field",
    variants: ["default"],
    firstSeen: "Log in",
  },
  {
    name: "Divider",
    figma: "Divider",
    variants: ["horizontal", "vertical"],
    firstSeen: "Log in",
  },
  {
    name: "Card",
    figma: "Content",
    variants: ["default"],
    firstSeen: "Log in",
  },
  {
    name: "Logo",
    figma: "SouthEast Bank logo",
    variants: ["default"],
    firstSeen: "Log in",
  },
  {
    name: "FooterDisclaimer",
    figma: "Footer Disclaimer",
    variants: ["default"],
    firstSeen: "Log in",
  },
  {
    name: "Loader",
    figma: "Login submit state",
    variants: ["default", "inline"],
    firstSeen: "Log in",
  },
  {
    name: "FiltersPanel",
    figma: "Filters",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "NotesPanel",
    figma: "Notes",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "DecisionPanel",
    figma: "Application Decision",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "PasscodeField",
    figma: "Number Indicator",
    variants: ["6-digit"],
    firstSeen: "Magic link sent",
  },
  {
    name: "PageHeader",
    figma: "Page header",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "SearchField",
    figma: "Search",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "FilterTags",
    figma: "Filter tags",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
  {
    name: "DataTable",
    figma: "Table",
    variants: ["comfortable", "compact"],
    firstSeen: "Flight Deck",
  },
  {
    name: "Pagination",
    figma: "Pagination",
    variants: ["default"],
    firstSeen: "Flight Deck",
  },
] as const;
