import { seedApplications } from "./mock-data";
import type {
  Certification,
  Disbursement,
  DisbursementStatus,
  OpsState,
  ServicingCase,
  ServicingLoan,
} from "./ops-types";

export const ADVISORS = ["Morgan Struchko", "Nathan", "Liz", "Bini Phillip", "Chris Stamm"];

function at(date: string, hour = 12) {
  return `${date}T${String(hour).padStart(2, "0")}:00:00`;
}

function disb(id: string, date: string, amount: number, status: DisbursementStatus): Disbursement {
  return { id, date: at(date), amount, status };
}

function round2(value: number) {
  return Math.round(value * 100) / 100;
}

export function createOpsSeed(): OpsState {
  const inSchool = seedApplications.filter((app) => app.recordType === "InSchool");
  const refi = seedApplications.filter((app) => app.recordType === "ReFi");
  const linked = inSchool.slice(0, 3);
  const reduced = inSchool[3];
  const first = linked[0]!;
  const second = linked[1]!;
  const third = linked[2]!;
  const fourth = reduced!;
  const refiLoan = refi[0]!;
  const refiPending = refi[1]!;
  const refiDone = refi[2]!;

  const certifications: Certification[] = [
    {
      id: "cert-1001",
      applicationId: first.id,
      borrower: first.borrower.fullName,
      product: "InSchool",
      school: first.borrower.school,
      schoolCode: "001381",
      requestedAt: at("2026-08-12", 9),
      certifiedAt: null,
      approvedAmount: first.amount,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "requested",
      disbursements: [],
    },
    {
      id: "cert-1002",
      applicationId: second.id,
      borrower: second.borrower.fullName,
      product: "InSchool",
      school: second.borrower.school,
      schoolCode: "001381",
      requestedAt: at("2026-09-04", 9),
      certifiedAt: null,
      approvedAmount: second.amount,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "requested",
      disbursements: [],
    },
    {
      id: "cert-1003",
      applicationId: null,
      borrower: "Amelia Cho",
      product: "EdMed",
      school: "Vanderbilt University",
      schoolCode: "003535",
      requestedAt: at("2026-09-18", 10),
      certifiedAt: null,
      approvedAmount: 42000,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "requested",
      disbursements: [],
    },
    {
      id: "cert-1004",
      applicationId: null,
      borrower: "Noah Ibarra",
      product: "EdMed",
      school: "Tufts University",
      schoolCode: "002219",
      requestedAt: at("2026-09-26", 11),
      certifiedAt: null,
      approvedAmount: 38500,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "requested",
      disbursements: [],
    },
    {
      id: "cert-1005",
      applicationId: null,
      borrower: "Helena Voss",
      product: "InSchool",
      school: "University of Michigan",
      schoolCode: "002325",
      requestedAt: at("2026-07-20", 9),
      certifiedAt: null,
      approvedAmount: 18000,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "rejected",
      disbursements: [],
    },
    {
      id: "cert-1006",
      applicationId: third.id,
      borrower: third.borrower.fullName,
      product: "InSchool",
      school: third.borrower.school,
      schoolCode: "001381",
      requestedAt: at("2026-08-20", 9),
      certifiedAt: at("2026-09-01", 15),
      approvedAmount: third.amount,
      certifiedAmount: third.amount,
      costOfAttendance: round2(third.amount * 1.35),
      enrollment: "full-time",
      status: "certified",
      disbursements: [disb("d-1006", "2026-09-18", round2(third.amount / 2), "scheduled")],
    },
    {
      id: "cert-1007",
      applicationId: null,
      borrower: "Priya Raman",
      product: "EdMed",
      school: "Emory University",
      schoolCode: "001564",
      requestedAt: at("2026-09-02", 9),
      certifiedAt: at("2026-09-12", 14),
      approvedAmount: 45000,
      certifiedAmount: 45000,
      costOfAttendance: 68200,
      enrollment: "full-time",
      status: "certified",
      disbursements: [disb("d-1007", "2026-10-01", 22500, "scheduled")],
    },
    {
      id: "cert-1008",
      applicationId: fourth.id,
      borrower: fourth.borrower.fullName,
      product: "InSchool",
      school: fourth.borrower.school,
      schoolCode: "001381",
      requestedAt: at("2026-08-28", 9),
      certifiedAt: at("2026-09-08", 16),
      approvedAmount: fourth.amount,
      certifiedAmount: round2(fourth.amount * 0.8),
      costOfAttendance: round2(fourth.amount * 1.1),
      enrollment: "half-time",
      status: "reduced",
      disbursements: [disb("d-1008", "2026-11-16", round2(fourth.amount * 0.4), "scheduled")],
    },
    {
      id: "cert-1009",
      applicationId: null,
      borrower: "Jonah Ellis",
      product: "EdMed",
      school: "Johns Hopkins University",
      schoolCode: "002077",
      requestedAt: at("2026-08-10", 9),
      certifiedAt: at("2026-08-22", 13),
      approvedAmount: 52000,
      certifiedAmount: 40000,
      costOfAttendance: 71000,
      enrollment: "full-time",
      status: "reduced",
      disbursements: [disb("d-1009", "2026-09-08", 20000, "scheduled")],
    },
    {
      id: "cert-1010",
      applicationId: null,
      borrower: "Sana Okoye",
      product: "InSchool",
      school: "Northridge College",
      schoolCode: "003456",
      requestedAt: at("2026-08-15", 9),
      certifiedAt: at("2026-08-29", 11),
      approvedAmount: 24000,
      certifiedAmount: 24000,
      costOfAttendance: 31000,
      enrollment: "full-time",
      status: "certified",
      disbursements: [
        disb("d-1010-a", "2026-12-04", 12000, "scheduled"),
        disb("d-1010-b", "2027-01-15", 12000, "scheduled"),
      ],
    },
    {
      id: "cert-1011",
      applicationId: null,
      borrower: "Claire Adeyemi",
      product: "EdMed",
      school: "Medical College of Wisconsin",
      schoolCode: "003156",
      requestedAt: at("2026-07-28", 9),
      certifiedAt: at("2026-08-06", 15),
      approvedAmount: 36000,
      certifiedAmount: 36000,
      costOfAttendance: 54000,
      enrollment: "full-time",
      status: "certified",
      disbursements: [
        disb("d-1011-a", "2026-08-15", 18000, "disbursed"),
        disb("d-1011-b", "2026-10-15", 18000, "scheduled"),
      ],
    },
    {
      id: "cert-1012",
      applicationId: null,
      borrower: "Mateo Ruiz",
      product: "InSchool",
      school: "University of Georgia",
      schoolCode: "001598",
      requestedAt: at("2026-09-01", 9),
      certifiedAt: at("2026-09-14", 10),
      approvedAmount: 15000,
      certifiedAmount: 15000,
      costOfAttendance: 22000,
      enrollment: "full-time",
      status: "certified",
      disbursements: [disb("d-1012", "2026-09-28", 7500, "scheduled")],
    },
    {
      id: "cert-1013",
      applicationId: refi[3]!.id,
      borrower: refi[3]!.borrower.fullName,
      product: "ReFi",
      school: refi[3]!.borrower.school,
      schoolCode: "009100",
      requestedAt: at("2026-09-22", 9),
      certifiedAt: null,
      approvedAmount: refi[3]!.amount,
      certifiedAmount: null,
      costOfAttendance: null,
      enrollment: "",
      status: "requested",
      disbursements: [],
    },
    {
      id: "cert-1014",
      applicationId: refi[4]!.id,
      borrower: refi[4]!.borrower.fullName,
      product: "ReFi",
      school: refi[4]!.borrower.school,
      schoolCode: "009100",
      requestedAt: at("2026-08-18", 9),
      certifiedAt: at("2026-09-03", 11),
      approvedAmount: refi[4]!.amount,
      certifiedAmount: refi[4]!.amount,
      costOfAttendance: round2(refi[4]!.amount * 1.2),
      enrollment: "full-time",
      status: "certified",
      disbursements: [disb("d-1014", "2026-09-20", round2(refi[4]!.amount / 2), "scheduled")],
    },
  ];

  const loans: ServicingLoan[] = [
    loanFromCert(certifications[5]!, "loan-5001", "Mohela", "completed", "2026-09-05", 0, 0),
    loanFromCert(certifications[6]!, "loan-5002", "Nelnet", "pending", null, 0, 0),
    loanFromCert(certifications[7]!, "loan-5003", "Mohela", "completed", "2026-09-10", 0, 0),
    loanFromCert(certifications[8]!, "loan-5004", "Mohela", "completed", "2026-09-01", 0, 0),
    loanFromCert(certifications[9]!, "loan-5005", "Nelnet", "completed", "2026-09-02", 0, 0),
    loanFromCert(certifications[10]!, "loan-5006", "Mohela", "completed", "2026-08-18", 18000, 210),
    loanFromCert(certifications[11]!, "loan-5007", "Nelnet", "pending", null, 0, 0),
    {
      id: "loan-5008",
      certificationId: null,
      applicationId: refiLoan.id,
      borrower: refiLoan.borrower.fullName,
      product: "ReFi",
      school: "",
      schoolCode: "",
      servicer: "Mohela",
      boardedAt: at("2026-09-12", 8),
      boardingStatus: "completed",
      principal: refiLoan.amount,
      interest: round2(refiLoan.amount * 0.004),
      disbursements: [disb("d-5008", "2026-09-12", refiLoan.amount, "disbursed")],
      readOnly: true,
    },
    {
      id: "loan-5009",
      certificationId: null,
      applicationId: refiDone.id,
      borrower: refiDone.borrower.fullName,
      product: "ReFi",
      school: "",
      schoolCode: "",
      servicer: "Mohela",
      boardedAt: at("2026-09-20", 8),
      boardingStatus: "completed",
      principal: refiDone.amount,
      interest: round2(refiDone.amount * 0.003),
      disbursements: [disb("d-5009", "2026-09-20", refiDone.amount, "disbursed")],
      readOnly: true,
    },
    {
      id: "loan-5010",
      certificationId: null,
      applicationId: refiPending.id,
      borrower: refiPending.borrower.fullName,
      product: "ReFi",
      school: "",
      schoolCode: "",
      servicer: "Mohela",
      boardedAt: null,
      boardingStatus: "pending",
      principal: refiPending.amount,
      interest: 0,
      disbursements: [disb("d-5010", "2026-09-30", refiPending.amount, "scheduled")],
      readOnly: true,
    },
    loanFromCert(certifications.find((item) => item.id === "cert-1014")!, "loan-5011", "Mohela", "pending", null, 0, 0),
  ];

  const cases: ServicingCase[] = [
    {
      id: "case-3001",
      loanId: "loan-5001",
      type: "disbursement-review",
      priority: "high",
      status: "open",
      openedBy: "Morgan Struchko",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-18", 8),
      details: "School disbursement date has passed and the funds are still scheduled. Confirm the roster before release.",
      notes: "",
    },
    {
      id: "case-3002",
      loanId: "loan-5002",
      type: "disbursement-change",
      priority: "high",
      status: "open",
      openedBy: "Bini Phillip",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-30", 9),
      details: "Borrower asked to move the first disbursement. School date is today, so this needs a same-day review.",
      notes: "Borrower called and asked for the fall disbursement to be split.",
    },
    {
      id: "case-3003",
      loanId: "loan-5003",
      type: "school-code",
      priority: "medium",
      status: "waiting-on-school",
      openedBy: "Morgan Struchko",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-11", 14),
      details: "Certified amount is below the approval. Confirm the school code before the November disbursement is scheduled.",
      notes: "",
    },
    {
      id: "case-3004",
      loanId: "loan-5004",
      type: "disbursement-review",
      priority: "high",
      status: "open",
      openedBy: "Nathan",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-08", 10),
      details: "EdMed certification was reduced and the disbursement date has passed. Review the certified amount against cost of attendance.",
      notes: "",
    },
    {
      id: "case-3005",
      loanId: "loan-5005",
      type: "borrower-follow-up",
      priority: "low",
      status: "waiting-on-advisor",
      openedBy: "Morgan Struchko",
      assignee: "Liz",
      openedAt: at("2026-09-16", 11),
      details: "Borrower asked when the spring disbursement will show on the school account. No change to the certified dates.",
      notes: "Reassigned to Liz to call the borrower back.",
    },
    {
      id: "case-3006",
      loanId: "loan-5006",
      type: "resend-certification",
      priority: "medium",
      status: "open",
      openedBy: "Chris Stamm",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-22", 15),
      details: "School asked for the certification to be resent before the October disbursement. First disbursement already went out.",
      notes: "",
    },
    {
      id: "case-3007",
      loanId: "loan-5007",
      type: "borrower-follow-up",
      priority: "medium",
      status: "open",
      openedBy: "Bini Phillip",
      assignee: "Nathan",
      openedAt: at("2026-09-29", 13),
      details: "Disbursement was scheduled for September 28 and has not been released. Borrower is asking for status.",
      notes: "",
    },
    {
      id: "case-3008",
      loanId: "loan-5001",
      type: "borrower-follow-up",
      priority: "low",
      status: "resolved",
      openedBy: "Liz",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-06", 9),
      details: "Borrower confirmed the fall enrollment after certification.",
      notes: "Spoke with the borrower. Enrollment matches the school certification.",
    },
    {
      id: "case-3009",
      loanId: "loan-5011",
      type: "disbursement-review",
      priority: "high",
      status: "open",
      openedBy: "Morgan Struchko",
      assignee: "Morgan Struchko",
      openedAt: at("2026-09-20", 9),
      details: "ReFi certification is scheduled and the disbursement date has passed. Review before release.",
      notes: "",
    },
  ];

  return { certifications, loans, cases };
}

function loanFromCert(
  cert: Certification,
  id: string,
  servicer: ServicingLoan["servicer"],
  boardingStatus: ServicingLoan["boardingStatus"],
  boardedOn: string | null,
  principal: number,
  interest: number,
): ServicingLoan {
  return {
    id,
    certificationId: cert.id,
    applicationId: cert.applicationId,
    borrower: cert.borrower,
    product: cert.product,
    school: cert.school,
    schoolCode: cert.schoolCode,
    servicer,
    boardedAt: boardedOn ? at(boardedOn, 8) : null,
    boardingStatus,
    principal,
    interest,
    disbursements: [],
    readOnly: false,
  };
}

export const opsSeed = createOpsSeed();
